### ISSUE TITLE
[Enhancement] Simplify Account Linking Process 

### ISSUE THREAD

**Issue by NotAussie** [MCUmbrella/MGBridge#2]
Hey there! So, I noticed that bind codes can be quite complex and make linking accounts more difficult than necessary. My suggestion is to switch to a simpler system where users can just run `/mgb link` in Minecraft, then use `/mgb link (username)` on Guilded, and finally confirm with `/mgb confirm` in Minecraft. This would make connecting accounts much easier. Best regards.

**Comment by MCUmbrella** [comment]
I've made the bind code simpler in the latest commit. Have a try.
